{{ if .Values.pullsecret.enabled }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ .Values.pullsecret.name }}
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - key: {{ .Values.pullsecret.name }}
      name: .dockerconfigjson
  {{ end }}
